// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SK_pair_MC_cpp_parallel
arma::mat SK_pair_MC_cpp_parallel(const arma::mat& X, int m, int n_threads);
RcppExport SEXP _MultiEFM_SK_pair_MC_cpp_parallel(SEXP XSEXP, SEXP mSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(SK_pair_MC_cpp_parallel(X, m, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// SK_subsample_fast_cpp_parallel
arma::mat SK_subsample_fast_cpp_parallel(const arma::mat& X, double rate, int n_threads);
RcppExport SEXP _MultiEFM_SK_subsample_fast_cpp_parallel(SEXP XSEXP, SEXP rateSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(SK_subsample_fast_cpp_parallel(X, rate, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// kenMultiRFM_cpp
Rcpp::List kenMultiRFM_cpp(const Rcpp::List& XsList, const int& q, const arma::vec& qs_vec, const double& subsample_rate, const int& factor_method, const int& sampling_method, const int& sample_pairs, const int& n_threads, const double& epsObj, const int& maxIter, const bool& verbose);
RcppExport SEXP _MultiEFM_kenMultiRFM_cpp(SEXP XsListSEXP, SEXP qSEXP, SEXP qs_vecSEXP, SEXP subsample_rateSEXP, SEXP factor_methodSEXP, SEXP sampling_methodSEXP, SEXP sample_pairsSEXP, SEXP n_threadsSEXP, SEXP epsObjSEXP, SEXP maxIterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type XsList(XsListSEXP);
    Rcpp::traits::input_parameter< const int& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type qs_vec(qs_vecSEXP);
    Rcpp::traits::input_parameter< const double& >::type subsample_rate(subsample_rateSEXP);
    Rcpp::traits::input_parameter< const int& >::type factor_method(factor_methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type sampling_method(sampling_methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type sample_pairs(sample_pairsSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsObj(epsObjSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(kenMultiRFM_cpp(XsList, q, qs_vec, subsample_rate, factor_method, sampling_method, sample_pairs, n_threads, epsObj, maxIter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// kenMultiRFM_project_cpp
Rcpp::List kenMultiRFM_project_cpp(const Rcpp::List& XsList, const int& q, const arma::vec& qs_vec, const double& subsample_rate, const int& factor_method, const int& n_threads, const double& epsObj, const int& maxIter, const bool& verbose);
RcppExport SEXP _MultiEFM_kenMultiRFM_project_cpp(SEXP XsListSEXP, SEXP qSEXP, SEXP qs_vecSEXP, SEXP subsample_rateSEXP, SEXP factor_methodSEXP, SEXP n_threadsSEXP, SEXP epsObjSEXP, SEXP maxIterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type XsList(XsListSEXP);
    Rcpp::traits::input_parameter< const int& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type qs_vec(qs_vecSEXP);
    Rcpp::traits::input_parameter< const double& >::type subsample_rate(subsample_rateSEXP);
    Rcpp::traits::input_parameter< const int& >::type factor_method(factor_methodSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsObj(epsObjSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(kenMultiRFM_project_cpp(XsList, q, qs_vec, subsample_rate, factor_method, n_threads, epsObj, maxIter, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiEFM_SK_pair_MC_cpp_parallel", (DL_FUNC) &_MultiEFM_SK_pair_MC_cpp_parallel, 3},
    {"_MultiEFM_SK_subsample_fast_cpp_parallel", (DL_FUNC) &_MultiEFM_SK_subsample_fast_cpp_parallel, 3},
    {"_MultiEFM_kenMultiRFM_cpp", (DL_FUNC) &_MultiEFM_kenMultiRFM_cpp, 11},
    {"_MultiEFM_kenMultiRFM_project_cpp", (DL_FUNC) &_MultiEFM_kenMultiRFM_project_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiEFM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
