# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SK_pair_MC_cpp_parallel <- function(X, m, n_threads = 0L) {
    .Call(`_MultiEFM_SK_pair_MC_cpp_parallel`, X, m, n_threads)
}

SK_subsample_fast_cpp_parallel <- function(X, rate = 0.7, n_threads = 0L) {
    .Call(`_MultiEFM_SK_subsample_fast_cpp_parallel`, X, rate, n_threads)
}

kenMultiRFM_cpp <- function(XsList, q, qs_vec, subsample_rate, factor_method, sampling_method, sample_pairs, n_threads, epsObj, maxIter, verbose) {
    .Call(`_MultiEFM_kenMultiRFM_cpp`, XsList, q, qs_vec, subsample_rate, factor_method, sampling_method, sample_pairs, n_threads, epsObj, maxIter, verbose)
}

kenMultiRFM_project_cpp <- function(XsList, q, qs_vec, subsample_rate, factor_method, n_threads, epsObj, maxIter, verbose) {
    .Call(`_MultiEFM_kenMultiRFM_project_cpp`, XsList, q, qs_vec, subsample_rate, factor_method, n_threads, epsObj, maxIter, verbose)
}

